export default [
  { "description": "Salário",     "amount": "1300.52", "type": "entrada", "frequency": "recorrente","category":"Saude", "date": "2020-01-10" }, 
  { "description": "Freela",      "amount": "150.13",  "type": "entrada", "frequency": "eventual","category":"Saude",   "date": "2020-01-17" }, 
  { "description": "Salário",     "amount": "2500.23", "type": "entrada", "frequency": "recorrente","category":"Saude", "date": "2020-02-10" }, 
  { "description": "Freela site", "amount": "900.23",  "type": "entrada", "frequency": "eventual","category":"Saude",   "date": "2020-02-21" }, 
  { "description": "Freela app",  "amount": "950.92",  "type": "entrada", "frequency": "eventual","category":"Saude",   "date": "2020-02-23" }, 
  { "description": "Salário",     "amount": "2500.25", "type": "entrada", "frequency": "recorrente", "category":"Saude","date": "2020-03-10" }, 
  { "description": "Salário",     "amount": "2500.18", "type": "entrada", "frequency": "recorrente","category":"Saude", "date": "2020-04-10" }, 
  { "description": "Salário",     "amount": "2500.15", "type": "entrada", "frequency": "recorrente","category":"Saude", "date": "2020-05-10" }, 
  { "description": "Salário",     "amount": "2500.12", "type": "entrada", "frequency": "recorrente","category":"Saude", "date": "2020-06-10" }, 
  { "description": "Salário",     "amount": "2500.00", "type": "entrada", "frequency": "recorrente","category":"Saude", "date": "2020-07-10" },
  { "description": "Saldo Betway","amount": "50.00",   "type": "entrada", "frequency": "eventual","category":"Saude",   "date": "2019-11-29" },
  { "description": "Salário",     "amount": "150.00",  "type": "entrada", "frequency": "recorrente","category":"Saude", "date": "2020-12-10" },
  { "description": "frella ASCII","amount": "150.00",  "type": "entrada", "frequency": "eventual",  "category":"Saude", "date": "2020-12-10" },
  { "description": "Salário",     "amount": "2500.00", "type": "entrada", "frequency": "recorrente","category":"Saude", "date": "2021-01-10" },
  { "description": "Saldo Betway","amount": "50.00",   "type": "entrada", "frequency": "eventual","category":"Saude",   "date": "2021-01-29" },
  { "description": "Salário",     "amount": "150.00",  "type": "entrada", "frequency": "recorrente","category":"Saude", "date": "2021-01-10" },
  { "description": "frella ASCII","amount": "150.00",  "type": "entrada", "frequency": "eventual",  "category":"Saude", "date": "2021-01-10" },
  { "description": "Teste Feb",   "amount": "150.00",  "type": "entrada", "frequency": "eventual",  "category":"Saude", "date": "2021-02-10" },
  { "description": "Salário",     "amount": "150.00",  "type": "entrada", "frequency": "recorrente","category":"Saude", "date": "2021-02-10" },
  { "description": "frella ASCII","amount": "150.00",  "type": "entrada", "frequency": "eventual",  "category":"Saude", "date": "2021-02-10" },
  { "description": "Teste Feb",   "amount": "150.00",  "type": "entrada", "frequency": "eventual",  "category":"Saude", "date": "2021-02-10" },
]