export default [
    {"description":"Energia elétrica","isGain":"true","amount":"350.55","type":"saída","frequency":"recorrente","category":"Saude","date":"2020-01-10"},
    {"description":"Água",            "isGain":"true","amount":"75.55", "type":"saída","frequency":"recorrente","category":"Saude","date":"2020-01-15"},
    {"description": "Telefone",       "isGain":"true","amount":"99.99", "type":"saída","frequency":"recorrente","category":"Saude","date":"2020-01-23"},
    {"description":"Plano de Saúde",  "isGain":"true","amount":"300.00","type":"saída","frequency":"recorrente","category":"Saude","date":"2020-01-23"},
    {"description":"Compras do mês",  "isGain":"true","amount":"625.78","type":"saída","frequency":"recorrente","category":"Saude","date":"2020-01-23"},
    { "description": "Salário",     "isGain":"true","amount": "1300.52", "type": "entrada", "frequency": "recorrente","category":"Saude", "date": "2020-01-9" }, 
    { "description": "Freela CBLAO","isGain":"true","amount": "150.13",  "type": "saída", "frequency": "eventual","category":"Saude",   "date": "2020-01-10" }, 
    { "description": "Salário",     "isGain":"true","amount": "2500.23", "type": "entrada", "frequency": "recorrente","category":"Saude", "date": "2020-02-10" }, 
    { "description": "Freela site", "isGain":"true","amount": "900.23",  "type": "entrada", "frequency": "eventual","category":"Saude",   "date": "2020-02-21" }, 
    { "description": "Freela app",  "isGain":"true","amount": "950.92",  "type": "saída", "frequency": "eventual","category":"Saude",   "date": "2020-02-23" }, 
    { "description": "Salário T1",     "isGain":"true","amount": "2500.25", "type": "saída", "frequency": "recorrente", "category":"Saude","date": "2020-03-09" }, 
    { "description": "Salário T2",     "isGain":"true","amount": "2500.25", "type": "entrada", "frequency": "recorrente", "category":"Saude","date": "2020-03-10" }, 
    { "description": "Salário",     "isGain":"true","amount": "2500.18", "type": "entrada", "frequency": "recorrente","category":"Saude", "date": "2020-04-10" }, 
    { "description": "Salário",     "isGain":"true","amount": "2500.18", "type": "saída", "frequency": "recorrente","category":"Saude", "date": "2020-04-10" }, 
    { "description": "Salário",     "isGain":"true","amount": "2500.15", "type": "entrada", "frequency": "recorrente","category":"Saude", "date": "2020-05-10" }, 
    { "description": "Salário",     "isGain":"true","amount": "2500.15", "type": "saída", "frequency": "recorrente","category":"Saude", "date": "2020-05-10" }, 
    { "description": "Salário",     "isGain":"true","amount": "2500.12", "type": "saída", "frequency": "recorrente","category":"Vestuário", "date": "2020-06-10" }, 
    { "description": "Salário",     "isGain":"true","amount": "2500.12", "type": "entrada", "frequency": "recorrente","category":"Saude", "date": "2020-06-10" }, 
    { "description": "Salário",     "isGain":"true","amount": "2500.00", "type": "saída", "frequency": "recorrente","category":"Saude", "date": "2020-07-10" },
    { "description": "Salário",     "isGain":"true","amount": "2500.00", "type": "entrada", "frequency": "recorrente","category":"Saude", "date": "2020-07-10" },
    { "description": "Saldo Betway","isGain":"true","amount": "50.00",   "type": "entrada", "frequency": "eventual","category":"Saude",   "date": "2019-11-29" },
    { "description": "Salário",    "isGain":"true", "amount": "150.00",  "type": "saída", "frequency": "recorrente","category":"Vestuário", "date": "2020-12-03" },
    { "description": "frella ASCII","isGain":"true","amount": "150.00",  "type": "entrada", "frequency": "eventual",  "category":"Lazer", "date": "2020-12-05" },
    { "description": "Salário",     "isGain":"true","amount": "150.00",  "type": "saída", "frequency": "recorrente","category":"Saude", "date": "2020-12-05" },
    { "description": "frella ASCII","isGain":"true","amount": "150.00",  "type": "entrada", "frequency": "eventual",  "category":"Alimento", "date": "2020-12-06" },
    { "description": "Salário",     "isGain":"true","amount": "150.00",  "type": "saída", "frequency": "recorrente","category":"Saude", "date": "2020-12-07" },
    { "description": "frella ASCII","isGain":"true","amount": "150.00",  "type": "entrada", "frequency": "eventual",  "category":"Salário", "date": "2020-12-10" },
    { "description": "Salário",     "isGain":"false","amount": "150.00",  "type": "saída", "frequency": "recorrente","category":"Saude", "date": "2020-12-10" },
    { "description": "frella ASCII","isGain":"false","amount": "150.00",  "type": "entrada", "frequency": "eventual",  "category":"Vestuário", "date": "2020-12-10" },
    { "description": "Salário",     "isGain":"false","amount": "150.00",  "type": "saída", "frequency": "recorrente","category":"Saude", "date": "2020-12-10" },
    { "description": "frella ASCII","isGain":"false","amount": "150.00",  "type": "entrada", "frequency": "eventual",  "category":"Saude", "date": "2020-12-10" },
    { "description": "Salário",     "isGain":"false","amount": "150.00",  "type": "saída", "frequency": "recorrente","category":"Saude", "date": "2020-12-10" },
    { "description": "frella ASCII","isGain":"false","amount": "150.00",  "type": "entrada", "frequency": "eventual",  "category":"Saude", "date": "2020-12-10" },
    { "description": "Salário",     "isGain":"false","amount": "150.00",  "type": "saída", "frequency": "recorrente","category":"Saude", "date": "2020-12-10" },
    { "description": "frella ASCII","isGain":"false","amount": "150.00",  "type": "entrada", "frequency": "eventual",  "category":"Saude", "date": "2020-12-10" },
    { "description": "Salário",     "isGain":"false","amount": "150.00",  "type": "saída", "frequency": "recorrente","category":"Saude", "date": "2020-12-10" },
    { "description": "frella ASCII","isGain":"false","amount": "150.00",  "type": "entrada", "frequency": "eventual",  "category":"Saude", "date": "2020-12-10" },
    { "description": "Salário",     "isGain":"false","amount": "150.00",  "type": "saída", "frequency": "recorrente","category":"Saude", "date": "2020-12-10" },
    { "description": "frella ASCII","isGain":"false","amount": "150.00",  "type": "entrada", "frequency": "eventual",  "category":"Saude", "date": "2020-12-10" },
    { "description": "Salário",     "isGain":"false","amount": "150.00",  "type": "saída", "frequency": "recorrente","category":"Saude", "date": "2020-12-10" },
    { "description": "frella ASCII","isGain":"false","amount": "150.00",  "type": "entrada", "frequency": "eventual",  "category":"Saude", "date": "2020-12-10" },

]