
export default [
    {"description":"Água",            "isGain":"true","amount":"475.55", "type":"saída","frequency":"recorrente","category":"Lazer","date":"2020-01-15"},
    {"description": "Telefone",       "isGain":"false","amount":"299.99", "type":"saída","frequency":"recorrente","category":"Vestuário","date":"2020-01-23"},
    {"description": "Telefone",       "isGain":"true","amount":"299.99", "type":"saída","frequency":"recorrente","category":"Outro","date":"2020-01-23"},
    {"description":"Plano de Saúde",  "isGain":"true","amount":"300.00","type":"saída","frequency":"recorrente","category":"Alimento","date":"2020-01-23"},
    {"description":"Compras do mês",  "isGain":"true","amount":"125.78","type":"saída","frequency":"recorrente","category":"Salário","date":"2020-01-23"},

    {"description":"Energia elétrica","isGain":"true","amount":"1350.55","type":"saída","frequency":"recorrente","category":"Farmácia","date":"2020-02-10"},
    {"description": "Telefone",       "isGain":"true","amount":"1299.99", "type":"saída","frequency":"recorrente","category":"Lazer","date":"2020-02-23"},
    {"description": "Telefone",       "isGain":"true","amount":"1299.99", "type":"saída","frequency":"recorrente","category":"Alimento","date":"2020-02-23"},
    {"description":"Plano de Saúde",  "isGain":"false","amount":"1300.00","type":"saída","frequency":"recorrente","category":"Outro","date":"2020-02-23"},
    {"description":"Compras do mês",  "isGain":"true","amount":"1925.78","type":"saída","frequency":"recorrente","category":"Salário","date":"2020-02-23"},

    {"description":"Energia elétrica","isGain":"false","amount":"2350.55","type":"saída","frequency":"recorrente","category":"Farmácia","date":"2020-03-10"},
    {"description":"Água",            "isGain":"true","amount":"2475.55", "type":"saída","frequency":"recorrente","category":"Vestuário","date":"2020-03-15"},
    {"description": "Telefone",       "isGain":"true","amount":"2299.99", "type":"saída","frequency":"recorrente","category":"Alimento","date":"2020-03-23"},
    {"description":"Plano de Saúde",  "isGain":"false","amount":"2300.00","type":"saída","frequency":"recorrente","category":"Outro","date":"2020-03-23"},
    {"description":"Compras do mês",  "isGain":"true","amount":"2025.78","type":"saída","frequency":"recorrente","category":"Salário","date":"2020-03-23"},

    {"description":"Energia elétrica","isGain":"true","amount":"3350.55","type":"saída","frequency":"recorrente","category":"Farmácia","date":"2020-04-10"},
    {"description":"Água",            "isGain":"false","amount":"3475.55", "type":"saída","frequency":"recorrente","category":"Vestuário","date":"2020-04-15"},
    {"description": "Telefone",       "isGain":"true","amount":"3299.99", "type":"saída","frequency":"recorrente","category":"Lazer","date":"2020-04-23"},
    {"description":"Plano de Saúde",  "isGain":"true","amount":"3300.00","type":"saída","frequency":"recorrente","category":"Outro","date":"2020-04-23"},
    {"description":"Compras do mês",  "isGain":"false","amount":"3925.78","type":"saída","frequency":"recorrente","category":"Salário","date":"2020-04-23"},

    {"description":"Energia elétrica","isGain":"true","amount":"4350.55","type":"saída","frequency":"recorrente","category":"Farmácia","date":"2020-05-10"},
    {"description":"Água",            "isGain":"false","amount":"4475.55", "type":"saída","frequency":"recorrente","category":"Vestuário","date":"2020-05-15"},
    {"description": "Telefone",       "isGain":"false","amount":"4299.99", "type":"saída","frequency":"recorrente","category":"Lazer","date":"2020-05-23"},
    {"description": "Telefone",       "isGain":"true","amount":"4299.99", "type":"saída","frequency":"recorrente","category":"Alimento","date":"2020-05-23"},
    {"description":"Compras do mês",  "isGain":"true","amount":"4025.78","type":"saída","frequency":"recorrente","category":"Salário","date":"2020-05-23"},

    {"description":"Energia elétrica","isGain":"false","amount":"5350.55","type":"saída","frequency":"recorrente","category":"Farmácia","date":"2020-06-10"},
    {"description":"Água",            "isGain":"true","amount":"5475.55", "type":"saída","frequency":"recorrente","category":"Vestuário","date":"2020-06-15"},
    {"description": "Telefone",       "isGain":"true","amount":"5299.99", "type":"saída","frequency":"recorrente","category":"Lazer","date":"2020-06-23"},
    {"description": "Telefone",       "isGain":"false","amount":"5299.99", "type":"saída","frequency":"recorrente","category":"Alimento","date":"2020-06-23"},
    {"description":"Plano de Saúde",  "isGain":"true","amount":"5300.00","type":"saída","frequency":"recorrente","category":"Outro","date":"2020-06-23"},

    {"description":"Água",            "isGain":"true","amount":"6475.55", "type":"saída","frequency":"recorrente","category":"Vestuário","date":"2020-07-15"},
    {"description": "Telefone",       "isGain":"false","amount":"6299.99", "type":"saída","frequency":"recorrente","category":"Lazer","date":"2020-07-23"},
    {"description": "Telefone",       "isGain":"true","amount":"6299.99", "type":"saída","frequency":"recorrente","category":"Alimento","date":"2020-07-23"},
    {"description":"Plano de Saúde",  "isGain":"false","amount":"6300.00","type":"saída","frequency":"recorrente","category":"Outro","date":"2020-07-23"},
    {"description":"Compras do mês",  "isGain":"true","amount":"6625.78","type":"saída","frequency":"recorrente","category":"Salário","date":"2020-07-23"},

    {"description":"Energia elétrica","isGain":"true","amount":"7350.55","type":"saída","frequency":"recorrente","category":"Farmácia","date":"2020-08-10"},
    {"description": "Telefone",       "isGain":"true","amount":"7299.99", "type":"saída","frequency":"recorrente","category":"Lazer","date":"2020-08-23"},
    {"description": "Telefone",       "isGain":"false","amount":"7299.99", "type":"saída","frequency":"recorrente","category":"Alimento","date":"2020-08-23"},
    {"description":"Plano de Saúde",  "isGain":"true","amount":"7300.00","type":"saída","frequency":"recorrente","category":"Outro","date":"2020-08-23"},
    {"description":"Compras do mês",  "isGain":"false","amount":"7625.78","type":"saída","frequency":"recorrente","category":"Salário","date":"2020-08-23"},

    {"description":"Energia elétrica","isGain":"false","amount":"8350.55","type":"saída","frequency":"recorrente","category":"Farmácia","date":"2020-09-10"},
    {"description":"Água",            "isGain":"false","amount":"8475.55", "type":"saída","frequency":"recorrente","category":"Vestuário","date":"2020-09-15"},
    {"description": "Telefone",       "isGain":"true","amount":"8299.99", "type":"saída","frequency":"recorrente","category":"Alimento","date":"2020-09-23"},
    {"description":"Plano de Saúde",  "isGain":"true","amount":"8300.00","type":"saída","frequency":"recorrente","category":"Outro","date":"2020-09-23"},
    {"description":"Compras do mês",  "isGain":"true","amount":"8625.78","type":"saída","frequency":"recorrente","category":"Salário","date":"2020-09-23"},

    {"description":"Energia elétrica","isGain":"false","amount":"9350.55","type":"saída","frequency":"recorrente","category":"Farmácia","date":"2020-10-10"},
    {"description":"Água",            "isGain":"true","amount":"9475.55", "type":"saída","frequency":"recorrente","category":"Vestuário","date":"2020-10-15"},
    {"description": "Telefone",       "isGain":"true","amount":"9299.99", "type":"saída","frequency":"recorrente","category":"Lazer","date":"2020-10-23"},
    {"description":"Plano de Saúde",  "isGain":"false","amount":"9300.00","type":"saída","frequency":"recorrente","category":"Outro","date":"2020-10-23"},
    {"description":"Compras do mês",  "isGain":"true","amount":"9625.78","type":"saída","frequency":"recorrente","category":"Salário","date":"2020-10-23"},

    {"description":"Energia elétrica","isGain":"true","amount":"10350.55","type":"saída","frequency":"recorrente","category":"Farmácia","date":"2020-11-10"},
    {"description":"Água",            "isGain":"false","amount":"10475.55", "type":"saída","frequency":"recorrente","category":"Vestuário","date":"2020-11-15"},
    {"description": "Telefone",       "isGain":"true","amount":"10299.99", "type":"saída","frequency":"recorrente","category":"Lazer","date":"2020-11-23"},
    {"description": "Telefone",       "isGain":"false","amount":"10299.99", "type":"saída","frequency":"recorrente","category":"Alimento","date":"2020-11-23"},
    {"description":"Compras do mês",  "isGain":"true","amount":"10625.78","type":"saída","frequency":"recorrente","category":"Salário","date":"2020-11-23"},

    {"description":"Energia elétrica","isGain":"true","amount":"11350.55","type":"saída","frequency":"recorrente","category":"Farmácia","date":"2020-12-10"},
    {"description":"Água",            "isGain":"true","amount":"11475.55", "type":"saída","frequency":"recorrente","category":"Vestuário","date":"2020-12-15"},
    {"description": "Telefone",       "isGain":"false","amount":"11299.99", "type":"saída","frequency":"recorrente","category":"Lazer","date":"2020-12-23"},
    {"description": "Telefone",       "isGain":"true","amount":"11299.99", "type":"saída","frequency":"recorrente","category":"Alimento","date":"2020-12-23"},
    {"description":"Plano de Saúde",  "isGain":"true","amount":"11300.00","type":"saída","frequency":"recorrente","category":"Outro","date":"2020-12-23"},
    {"description":"Energia elétrica","isGain":"false","amount":"1.55","type":"saída","frequency":"recorrente","category":"Farmácia","date":"2020-12-10"},
    {"description":"Água",            "isGain":"true","amount":"1.55", "type":"saída","frequency":"recorrente","category":"Vestuário","date":"2020-12-15"},
    {"description": "Telefone",       "isGain":"true","amount":"1.99", "type":"saída","frequency":"recorrente","category":"Lazer","date":"2020-12-23"},
    {"description": "Telefone",       "isGain":"false","amount":"1.99", "type":"saída","frequency":"recorrente","category":"Alimento","date":"2020-12-23"},
    {"description":"Plano de Saúde",  "isGain":"true","amount":"1.00","type":"saída","frequency":"recorrente","category":"Outro","date":"2020-12-23"},
]